apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: do-htop
spec:
  selector:
    matchLabels:
      name: do-htop
  template:
    metadata:
      labels:
        name: do-htop
    spec:
      containers:
        - name: do-htop
          image: iankoulski/do-htop:latest
          command: ["/bin/bash"]
          args: ["-c", "while true; do date; sleep 10; done"]
